/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.solutec.ihm;

import fr.solutec.dao.UserDao;
import fr.solutec.model.User;

import javax.swing.JOptionPane;

/**
 *
 * @author Joel B
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private static User u;
    
    public Home(User u) {
        
        initComponents();
        this.u = u;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btObj = new javax.swing.JButton();
        btActivite = new javax.swing.JButton();
        lbBienvenue = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbDateCo = new javax.swing.JLabel();
        btAide = new javax.swing.JButton();
        btProfil = new javax.swing.JButton();
        btDeconnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btObj.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        btObj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/objectifs.png"))); // NOI18N
        btObj.setText("Mes objectifs");
        btObj.setToolTipText("");
        btObj.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btActivite.setFont(new java.awt.Font("Eras Light ITC", 1, 24)); // NOI18N
        btActivite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/table.jpg"))); // NOI18N
        btActivite.setText("  Mes activités");
        btActivite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btActivite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActiviteActionPerformed(evt);
            }
        });

        lbBienvenue.setFont(new java.awt.Font("Eras Light ITC", 1, 18)); // NOI18N
        lbBienvenue.setText("Message d'accueil");

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        lbDateCo.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        lbDateCo.setText("Date derniere co");

        btAide.setBackground(new java.awt.Color(153, 204, 255));
        btAide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/help_s.png"))); // NOI18N
        btAide.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btAide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAideActionPerformed(evt);
            }
        });

        btProfil.setBackground(new java.awt.Color(153, 204, 255));
        btProfil.setText("Mon Profil");
        btProfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProfilActionPerformed(evt);
            }
        });

        btDeconnect.setBackground(new java.awt.Color(153, 204, 255));
        btDeconnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-débloquer-privé-50.png"))); // NOI18N
        btDeconnect.setText("Déconnection");
        btDeconnect.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btDeconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeconnectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btProfil, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(btDeconnect, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btAide, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDateCo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(128, 128, 128))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btDeconnect, btProfil});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAide)
                .addGap(51, 51, 51)
                .addComponent(btProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDeconnect)
                .addGap(27, 27, 27)
                .addComponent(lbDateCo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btDeconnect, btProfil});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btObj, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btActivite, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lbBienvenue)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btActivite, btObj});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbBienvenue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btObj, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btActivite, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbBienvenue.setText("Bienvenue " + u.getPrenom() + " ! ");
        
        if(u.getDateCo() == null){
            Aide fnAide = new Aide();
            fnAide.setVisible(true);
        }else{ 
            lbDateCo.setText("Dernière connexion : " + u.getDateCo());
        }
        
        if(u.getPoids() == 0) {
            JOptionPane.showMessageDialog(rootPane, "N'oubliez pas de rentrer votre poids dans l'onglet 'Mon Profil'");
        }
        
        if(u.getAge() == 0) {
            JOptionPane.showMessageDialog(rootPane, "N'oubliez pas de rentrer votre âge dans l'onglet 'Mon Profil'");
        }
        
       if(u.getTaille()== 0) {
            JOptionPane.showMessageDialog(rootPane, "N'oubliez pas de rentrer votre taille dans l'onglet 'Mon Profil'");
        }        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void btActiviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActiviteActionPerformed
        
        RecapAct fnActivite = new RecapAct(u);
        fnActivite.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btActiviteActionPerformed

    private void btDeconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeconnectActionPerformed

        try {
            Connection fnConnect = new Connection();
            UserDao.MajDateCo(u);
            fnConnect.setVisible(true);
            this.setVisible(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_btDeconnectActionPerformed

    private void btProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProfilActionPerformed
        Profil fnProfil = new Profil(u);
        fnProfil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btProfilActionPerformed

    private void btAideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAideActionPerformed
        Aide fnAide = new Aide();
        fnAide.setVisible(true);
    }//GEN-LAST:event_btAideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(u).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActivite;
    private javax.swing.JButton btAide;
    private javax.swing.JButton btDeconnect;
    private javax.swing.JButton btObj;
    private javax.swing.JButton btProfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbBienvenue;
    private javax.swing.JLabel lbDateCo;
    // End of variables declaration//GEN-END:variables
}
